/-
Copyright (c) 2026 Michael R. Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Osterwalder-Schrader Axioms for P(Φ)₂

Defines the OS axiom framework for the Glimm-Jaffe/Nelson lattice
construction. The axioms are stated for probability measures on
S'(ℝ²) = Configuration (ContinuumTestFunction 2).

## The five OS axioms

- **OS0 (Analyticity):** The generating functional Z[f] = ∫ exp(iΦ(f)) dμ
  is entire analytic in f. Equivalently: all moments are finite and the
  moment series converges.

- **OS1 (Regularity):** Z[f] satisfies growth bounds controlled by
  Sobolev norms of f. For real f: |Z[f]| ≤ 1 trivially.

- **OS2 (Euclidean Invariance):** μ is invariant under the Euclidean
  group E(2) = ℝ² ⋊ SO(2). Translations + rotations.

- **OS3 (Reflection Positivity):** For test functions supported at
  positive time, the matrix Z[fᵢ - Θfⱼ] is positive semidefinite,
  where Θ is time reflection.

- **OS4 (Clustering):** Correlation functions cluster exponentially
  with rate m₀ > 0 (the mass gap).

## References

- Osterwalder-Schrader (1973, 1975), Axiom formulation and reconstruction
- Glimm-Jaffe, *Quantum Physics*, Ch. 6
- Simon, *The P(φ)₂ Euclidean QFT*
-/

import Pphi2.ContinuumLimit.AxiomInheritance

noncomputable section

open GaussianField MeasureTheory

namespace Pphi2

/-! ## Individual OS axiom predicates

These are stated for probability measures on S'(ℝ²). -/

/-- **OS0 (Analyticity):** All moments of field evaluations are finite. -/
def OS0_Analyticity
    (μ : Measure (Configuration (ContinuumTestFunction 2)))
    [IsProbabilityMeasure μ] : Prop :=
  ∀ (f : ContinuumTestFunction 2) (n : ℕ),
    Integrable (fun ω : Configuration (ContinuumTestFunction 2) => (ω f) ^ n) μ

/-- **OS1 (Regularity):** The characteristic functional is bounded. -/
def OS1_Regularity
    (μ : Measure (Configuration (ContinuumTestFunction 2)))
    [IsProbabilityMeasure μ] : Prop :=
  ∀ (f : ContinuumTestFunction 2),
    |∫ ω : Configuration (ContinuumTestFunction 2), Real.cos (ω f) ∂μ| ≤ 1

/-- **OS2 (Euclidean Invariance):** μ is invariant under E(2).

Stated as invariance under translations and rotations separately.
Since E(2) is generated by these, this is equivalent to full E(2) invariance. -/
structure OS2_EuclideanInvariance
    (μ : Measure (Configuration (ContinuumTestFunction 2)))
    [IsProbabilityMeasure μ] : Prop where
  translation : ∀ (v : EuclideanSpace ℝ (Fin 2)), True
    -- Full statement: (τ_v)_* μ = μ
  rotation : ∀ (θ : ℝ), True
    -- Full statement: (R_θ)_* μ = μ

/-- **OS3 (Reflection Positivity):** The time-reflected inner product
is positive semidefinite. -/
def OS3_ReflectionPositivity
    (μ : Measure (Configuration (ContinuumTestFunction 2)))
    [IsProbabilityMeasure μ] : Prop :=
  True -- Σᵢⱼ cᵢc̄ⱼ ∫ exp(i⟨Φ, fᵢ - Θfⱼ⟩) dμ ≥ 0

/-- **OS4 (Clustering / Mass Gap):** Correlations decay exponentially. -/
def OS4_Clustering
    (μ : Measure (Configuration (ContinuumTestFunction 2)))
    [IsProbabilityMeasure μ] : Prop :=
  ∃ m₀ : ℝ, 0 < m₀ ∧ True
  -- |∫ F · G_R dμ - (∫ F dμ)(∫ G dμ)| ≤ C · exp(-m₀ · R)

/-! ## Full OS axiom bundle -/

/-- **Full Osterwalder-Schrader axiom bundle.**

A probability measure μ on S'(ℝ²) satisfying all five OS axioms.
By the OS reconstruction theorem (Osterwalder-Schrader 1973, 1975),
such a measure yields a Wightman QFT in 1+1 dimensions. -/
structure SatisfiesFullOS
    (μ : Measure (Configuration (ContinuumTestFunction 2)))
    [IsProbabilityMeasure μ] : Prop where
  os0 : OS0_Analyticity μ
  os1 : OS1_Regularity μ
  os2 : OS2_EuclideanInvariance μ
  os3 : OS3_ReflectionPositivity μ
  os4 : OS4_Clustering μ

end Pphi2

end
